# Generated by Django 3.2.23 on 2023-12-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20231206_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='description',
            new_name='instructions',
        ),
    ]
