# Generated by Django 3.2.23 on 2023-12-13 14:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_recipes_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'ordering': ['pub_date'], 'verbose_name': 'Recipe'},
        ),
        migrations.AddField(
            model_name='recipes',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
