# Generated by Django 3.2.23 on 2023-12-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_recipes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
