# Generated by Django 3.2.23 on 2023-12-13 20:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_recipes_excerpt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipes',
            new_name='Recipe',
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['pub_date']},
        ),
    ]
