# Generated by Django 3.2.23 on 2023-12-14 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20231213_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blogrecipe_like', to=settings.AUTH_USER_MODEL),
        ),
     
    ]
