# Generated by Django 3.2.23 on 2024-04-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20240403_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=200),
        ),
    ]
